<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>aspnet-TSD2491Gruppe25.Web-1308f5b8-fc2f-45ae-9606-61012b9b9630</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <None Update="app.db" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.2"
   />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    </ItemGroup>

    <Target Name="BuildTailwind" BeforeTargets="Build">
      <Exec Command="npm install" Condition="!Exists('node_modules')" ContinueOnError="WarnAndContinue"
   />
      <Exec Command="npm run build:css" ContinueOnError="WarnAndContinue" />
    </Target>
<ItemGroup>
      <Compile Remove="Tests/**" />
      <Content Remove="Tests/**" />
      <None Remove="Tests/**" />
      <EmbeddedResource Remove="Tests/**" />
    </ItemGroup>
  </Project>
